SCI: Add support for Korean fan translation
scummvm/scummvm pull request #2604
Opened 2020-11-06 05:34 UTC by wonst719

This PR is part of scummvm-kor merge project.

The patch adds ability to load external Korean text resource file similar to Japanese version, and to display korean text with 2x multiplied resolution (also similar to Japanese version).
Unfortunately this is not enough for supporting all fan-translated games, as some translated games require more hack.
Once this PR is merged, I intend to work on more game support.

Tested with:
- Castle of Dr. Brain (Korean patched)

![scummvm-castlebrain-kr-00000](https://user-images.githubusercontent.com/2627281/98330166-1efe2c80-203d-11eb-9a14-406916365d0b.png)

2020-11-06 18:23 UTC, sev- commented
Looks good to me, thanks!

2020-11-06 18:58 UTC, sev- approved these changes

2020-11-08 02:41 UTC, sluicebox commented
This looks great and is very exciting! I had no idea there were so many Korean SCI translations.

Since GK1 Korean is high-res only, GAMEOPTION_HIGH_RESOLUTION_GRAPHICS should be removed from its DOS detection table entry, as it is for Windows CD and Mac. That prevents giving users an option that doesn't do anything and it means you don't need the GK1 exception you've added to GfxFrameout::detectHiRes(). High-res is the default with that option removed. The existing exceptions in that function are for known low-res versions.

I'd like to see the repeated message-map tests in resource.cpp moved into a function like isKoreanMessageMap() with a comment explaining why that needs to be handled differently. I spend a lot of time in resource.cpp, and as I'm sure you've noticed, it's understandably built up a lot of cryptic exceptions. =)

2020-11-08 13:39 UTC, bluegr commented on engines/sci/resource.cpp
> +	    !(getLocationName() == "message.map" && g_sci->getLanguage() == Common::KO_KOR)) {
Since this condition gets repeated 4 times, and it's for Korean only, it would be better if it was put in a separate function, e.g. isKoreanMap()

2020-11-08 13:40 UTC, bluegr commented on engines/sci/graphics/text32.cpp
> +	if (1/*(firstChar >= 0xA1) && (firstChar <= 0xFE)*/) {
If this is always true, then the checking should be removed

2020-11-08 13:42 UTC, bluegr commented on engines/sci/detection_tables.h
> +		Common::KO_KOR, Common::kPlatformDOS, ADGF_CD, GUIO5(GAMEOPTION_HIGH_RESOLUTION_GRAPHICS, GAMEOPTION_PREFER_DIGITAL_SFX, GAMEOPTION_ORIGINAL_SAVELOAD, GAMEOPTION_MIDI_MODE, GAMEOPTION_RGB_RENDERING
You can now use GUIO_KQ6_CD for the GUIO flags

2020-11-08 13:43 UTC, bluegr commented on engines/sci/detection_tables.h
> +		Common::KO_KOR, Common::kPlatformWindows, ADGF_CD, GUIO6(GUIO_NOASPECT, GAMEOPTION_HIGH_RESOLUTION_GRAPHICS, GAMEOPTION_KQ6_WINDOWS_CURSORS, GAMEOPTION_PREFER_DIGITAL_SFX, GAMEOPTION_ORIGINAL_SAVEL
You can now use GUIO_KQ6_CD_WINDOWS for the GUIO flags

2020-11-08 13:45 UTC, bluegr commented on engines/sci/graphics/cache.cpp
> +		else
Formatting

2020-11-08 13:46 UTC, bluegr commented on engines/sci/graphics/text32.cpp
> +    // GK1 Korean pathed version use doubled resolution for font
```suggestion
    // GK1 Korean patched version use doubled resolution for font
```

2020-11-08 13:49 UTC, bluegr commented on engines/sci/graphics/text16.cpp
> +// korean and then switch to font 1001
```suggestion
// Check for Korean strings, and use font 1001 to render them
```

2020-11-08 13:51 UTC, bluegr commented on engines/sci/graphics/text32.cpp
> +		// We need to check for Korean-EUCKR every line
Why do you need to check for Korean in each line? Could you store the result of this function in a variable and check that instead?

2020-11-08 13:52 UTC, bluegr commented on engines/sci/graphics/text32.cpp
> +				// We need to check for Korean-EUCKR every line
Same as above, why is this check needed for all text?

2020-11-08 13:53 UTC, bluegr commented on engines/sci/graphics/text32.cpp
> +// korean and then switch to font 1001
```suggestion
// Check for Korean strings, and use font 1001 to render them
```

2020-11-08 13:55 UTC, bluegr commented on graphics/korfont.cpp
> +		//return ((_drawMode == kOutlineMode) ? 10 : (_drawMode == kDefaultMode ? 8 : 9));
Dead code?

2020-11-08 13:58 UTC, bluegr commented on graphics/korfont.h
> +		kFeatFlipped		= 1 << 4
Please use spaces, not tabs for spacing

2020-11-08 14:01 UTC, bluegr requested changes
Overall, very nice work!
Some small changes are needed, and once the issues reported by @sluicebox and me are addressed, this can be merged :)

2020-11-08 17:12 UTC, wonst719 commented
I did some cleanup and applied requested changes.

2020-11-08 20:26 UTC, bluegr commented
Excellent, thanks!
The only leftover is the if check in SwitchToFont1001OnKorean(), but that can be fixed in-tree.

Many thanks for your work, merging

2020-11-08 20:26 UTC, bluegr approved these changes

2020-11-08 20:26 UTC, merged