DOXYGEN: doxygen review on remaining common headers
scummvm/scummvm pull request #2627
Opened 2020-11-17 01:03 UTC by b-gent

The PR covers the remaining high-priority headers from the common folder.

- textconsole.h
- timer.h
- translation.h
- ustr.h
- util.h

2020-11-17 01:03 UTC, b-gent commented
I'll fix the conflict tomorrow.

2020-11-17 22:32 UTC, b-gent commented
This is ready for review @sev-  @criezy

2020-11-18 23:14 UTC, criezy requested changes
First pass on `textconsole.h`, `timer.h`, and `translation.h`.
I will look at the other two files later this week.

2020-11-20 09:14 UTC, mgerhardy commented on common/translation.h
> +	/**
This looks like a whitespace issue

2020-11-20 09:16 UTC, mgerhardy commented on common/translation.h
> +	String msgctxt;    /*!< @todo Doc required. */
Can be used to solving ambiguities. Here are more details about it: https://www.gnu.org/software/gettext/manual/html_node/Contexts.html

2020-11-20 09:18 UTC, mgerhardy commented on common/ustr.h
> +	const uint32 *u32_str() const {   /*!< @todo Doc required (Return the number of characters in the string???) */
Returns the string as UTF-32 pointer

2020-11-20 09:19 UTC, mgerhardy commented on common/util.h
> + * @note Use _() to translate units correctly.
should this maybe be prefixed by `@c` (`@c _()`)

2020-11-22 00:02 UTC, b-gent commented
Comments fixed, thank you for reviews @criezy  and @mgerhardy 
This should be good to go now.

2020-11-22 16:56 UTC, criezy approved these changes
Thank you. This looks good now.
There is one minor issue that I will fix when merging.

2020-11-22 16:57 UTC, criezy commented
And merged.

2020-11-22 16:57 UTC, closed without merging