DOXYGEN: Review headers from 'audio'
scummvm/scummvm pull request #2655
Opened 2020-11-30 01:57 UTC by b-gent

This PR has 3 headers in scope of GSoD.
The files are:
- audiostream.h
- mixer.h
- timestamp.h

The rest of the files are only receiving a doxy group.

2020-11-30 02:14 UTC, b-gent commented
@criezy 
Output is here
https://b-gent.github.io/2655/db/d71/group__audio__audiostream.html

Overall not a huge amount to check here, I think.

2020-12-01 23:44 UTC, criezy requested changes
This looks very good.
It is almost ready to merge.

2020-12-01 23:44 UTC, criezy commented on audio/audiostream.h
> + * @todo A bit more might be needed here
I think it is fine like this. Although maybe we can highlight its specificity a bit more by adding `multiple`:
`A QueuingAudioStream class that allows for queuing multiple audio streams for playback.`

2020-12-01 23:44 UTC, criezy commented on audio/timestamp.h
> +	 * Check whether this timestamp describes an earlier moment in time than another timestamp. @todo very unsure if I understand this correctly
Yes, that is correct.

2020-12-01 23:51 UTC, b-gent commented
Comments fixed.

2020-12-01 23:54 UTC, criezy approved these changes
That was quick! And it is now good to merge.

2020-12-01 23:54 UTC, merged