WIP: COMMON: Added tracy profiler support
scummvm/scummvm pull request #2686
Opened 2020-12-15 22:17 UTC by mgerhardy

Frame based, on-demand profiler: https://github.com/wolfpld/tracy

Example for Little Big Adventure is included

WIP: it doesn't link yet.

2020-12-15 22:20 UTC, mgerhardy commented on configure
> +define_in_config_if_yes $_tracy 'FORBIDDEN_SYMBOL_ALLOW_ALL'
Hack until I know how to solve this in a better way.

2020-12-15 22:21 UTC, mgerhardy commented on devtools/create_project/create_project.cpp
> +	{            "tracy",                  "ENABLE_TRACY", false, false, "Tracy profiler support"},
This is also not yet done - will be finished if we can agree to include this - but `TRACY_ENABLE` must be given as define. That is not yet done here.

2020-12-17 10:16 UTC, sev- requested changes
I think this could be a good addition. I have a couple of question and notes, though.

2020-12-17 14:38 UTC, mgerhardy commented on .gitmodules
> +[submodule "common/tracy"]
Absolutely true - this is just for letting people play with it to decide whether a proper integration is worth the work. Just like to get feedback if I should continue to integrate it.

2020-12-17 16:19 UTC, mgerhardy commented on engines/twine/animations.cpp
> +	trace_scoped(setModelAnimation);
Added `traceScopedFunc` as the name must not always be the function name

2020-12-17 16:19 UTC, mgerhardy commented on common/trace.h
> +#define trace_value_scoped(name, x) ZoneNamedN(__tracy_scoped_##name, #name, true); ZoneValueV(__tracy_scoped_##name, (uint64_t)(x))
All renamed

2020-12-17 16:19 UTC, mgerhardy commented on common/trace.h
> +#endif
Done.

2020-12-17 16:21 UTC, mgerhardy commented on .gitmodules
> +[submodule "common/tracy"]
The "problem" that I see here is that it's not a single c++ source file - but a lot of different headers and a lot of c++ files. Also the capture files are save, but the network protocol might differ from version to version. So it's the best to keep the profiler ui and the profiler "server" in sync somehow.

2020-12-17 16:28 UTC, mgerhardy commented on configure
> +define_in_config_if_yes $_tracy 'FORBIDDEN_SYMBOL_ALLOW_ALL'
Do you have any hint for me on how to solve this? I think that profiling should never get delivered in a release build anyway. So maybe activating this isn't a real problem for local builds?

On could just get rid of `common/trace.h` and do the

```c++
#ifdef TRACE_ENABLE
#include "common/tracy/Tracy.hpp"
#endif
```

everywhere in the c++ files where tracing is desired. But that would imo pollute the code with too much Tracy specific stuff. I'm really open for suggestions on how to solve this in a clean and nice way.

2021-01-10 12:21 UTC, mgerhardy commented on .gitmodules
> +[submodule "common/tracy"]
The author is suggesting this as integration method, too - https://github.com/wolfpld/tracy/blob/master/manual/tracy.tex#L388

One could also just assume that people who want to profile can copy the source files manually to the proper location and the build system will pick it up if that files exist. This wouldn't be a problem for make - but for msvc you would most likely have to re-run create_project for it.

2021-01-10 12:24 UTC, mgerhardy commented on configure
> +define_in_config_if_yes $_tracy 'FORBIDDEN_SYMBOL_ALLOW_ALL'
I just can't find a better way to do this. Is it a problem to activate this for those builds where tracy is enabled? I mean, tracy wouldn't be enabled for the CI builds, so errors would directly pop up (as `FORBIDDEN_SYMBOL_ALLOW_ALL` wouldn't be defined here of course.

2021-02-13 16:30 UTC, closed without merging

2021-02-13 16:32 UTC, mgerhardy commented
Closing this one - the profiler doesn't play very well with "inner-frames" - e.g. TwinE has a lot of do-while loops inside the main engine loop. Tracy needs a clear start and end of a frame - this doesn't work very nice with those inner-frames.