GUI: Text display issue when editing text #12336
scummvm/scummvm pull request #2948
Opened 2021-04-12 15:58 UTC by Rohit-v-raj

2021-04-12 17:43 UTC, sev- commented on gui/widgets/editable.cpp
> +			g_gui.theme()->drawText(Common::Rect(x, y, x + width, y ), character,
This change does not follow our Code Formatting conventions. Please, pay attention to the spaces around braces.

2021-04-12 17:44 UTC, sev- commented
The commit log message does not conform to our Commit Guidelines.
The code change itself breaks the Code Formatting Guidelines.

The PR is not descriptive, what is "the issue"?

2021-04-12 18:28 UTC, Rohit-v-raj commented
When editing some text, for example in the search box, of the game name in the Edit Game dialog, the letter immediately after the text cursor is displayed lower than the rest of the text.

2021-04-12 19:24 UTC, criezy commented
See https://wiki.scummvm.org/index.php?title=Commit_Guidelines for the commit guidelines. And pay special attention to the commit message formatting section.

You can use interactive rebase with git to fix your commit message (and squash the two commits) and then force push to your fork. This will automatically update this pull request.

2021-04-12 19:33 UTC, criezy requested changes
Your commit is not a proper fix for the issue.
What I suspect it does is that it no longer redraw the character when the caret is blinking (since the draw rect height is now 0). But there is a reason why we are drawing the character here after erasing the caret. What you need to find is why the character is not drawn at the correct position and fix that position.

2021-04-22 00:49 UTC, criezy commented
@Rohit-v-raj Since there was no reply from you my request to change this pull request, and went ahead and fixed the bug myself. You can see the correct fix, and the reason of the bug in ba0dabd5c.

2021-04-22 00:49 UTC, closed without merging