DIRECTOR: many more games
scummvm/scummvm pull request #3627
Opened 2021-12-24 22:04 UTC by mistydemeo

This adds a very large number of new games, mostly but not entirely Japanese. I can write out some detailed compatibility notes on each game if requested. This also adds a new set of demos, which I can make available to ScummVM devs.

A few of these discs are sets of digital/interactive artwork and have no menu, so they have many files per detection entry.

I've also fixed Mac filesizes for a few games I tested out of my collection when I discovered that they were added before the Mac filesize bug was fixed.

2021-12-26 11:06 UTC, moralrecordings commented
Looks good, thank you!

2021-12-26 11:07 UTC, merged

2021-12-26 22:03 UTC, trembyle requested changes
Thanks, there is so much good stuff here! I added comments where I could find more information on the games and could suggest different titles. For most of these, I'll just take your word for it since I don't have copies. In most cases, I haven't even heard of them!

Also, some generic filenames will need a second file to prevent the game being detected as a false positive.

2021-12-26 22:03 UTC, trembyle commented on engines/director/detection_tables.h
> +
Please add second files for both of these.

2021-12-26 22:07 UTC, trembyle commented
Since @moralrecordings merged this during my review, please submit the changes as a separate PR.

2021-12-26 22:19 UTC, mistydemeo commented on engines/director/detection_tables.h
> +	{ "dieveteranen",		"Die Veteranen" },
See below - Venetian Deer is a different item from the same group. Die Veteranen is the name of the group making it, but one of their releases was self-titled.

2021-12-27 18:05 UTC, mistydemeo commented on engines/director/detection_tables.h
> +	{ "venetiandeer",		"Venetian Deer" },
Different; Die Veteranen is the name of the group of artists, who self-titled one of their releases. Venetian Deer includes German/English bilingual documentation.

2021-12-27 18:22 UTC, trembyle commented on engines/director/detection_tables.h
> +	{ "venetiandeer",		"Venetian Deer" },
I see. Is the Venetian Deer software bilingual or just the documentation? If it's available in English, then this should be moved up to the English multimedia section.

2021-12-27 19:11 UTC, mistydemeo commented on engines/director/detection_tables.h
> +	{ "venetiandeer",		"Venetian Deer" },
As far as I can tell, there's not really any text in the artwork itself. The package you linked earlier is from Germany and uses both German and English text interchangeably.

2021-12-27 21:34 UTC, trembyle commented on engines/director/detection_tables.h
> +	{ "venetiandeer",		"Venetian Deer" },
Given the amount of English language on the packaging, and the fact that it does not require the user to know any German, I think this should be labeled as English. The CD that I linked came from Germany but was sold in the UK (at least according to the Discogs user who posted it).