DIRECTOR: LINGO: Implement traceLogFile Lingo Property
scummvm/scummvm pull request #4031
Opened 2022-06-21 20:32 UTC by r41k0u

This change implements traceLogFile and the required function in g_debugger. There is a new wrapper of debugPrintf which will log the stdout and stderr output in the log file specified. Functionality has been tested and us found consistent to that of the original

2022-06-21 23:31 UTC, sev- requested changes
Needs more work

2022-06-22 04:45 UTC, r41k0u commented on engines/director/debugger.cpp
> +		Common::DumpFile out;
That would present a problem.
What if the filename changes during the session, as in the test movie? In that case, a new log file is created, and both the logfiles exist. Closing the DumpFile object only once per session won't be able to handle change of log file name when the movie is running.

2022-06-22 05:10 UTC, r41k0u commented on engines/director/lingo/lingo-the.cpp
> +			g_director->_traceLogFile = ConfMan.get("path") + "/" + d.asString();
I have used FSNode's isWriteable() to test the same now. Is that fine or I shall go by the seeking method?

2022-06-22 07:59 UTC, r41k0u commented on engines/director/debugger.cpp
> +		Common::DumpFile out;
Nevermind, I was abe to find a workaround which would do what you had advised and also solve the above problem

2022-06-22 13:16 UTC, sev- commented on engines/director/lingo/lingo-the.cpp
> +			g_director->_traceLogFile = ConfMan.get("path") + "/" + d.asString();
Yes, this would work.

2022-06-28 20:15 UTC, sev- commented
THis has to be rebased and code formatting fixed.

2022-07-02 10:57 UTC, sev- commented
Hello? @r41k0u

2022-07-02 20:44 UTC, sev- commented
Merging, however, I will add after this a `warning()` if the log file is not writeable.

2022-07-02 20:44 UTC, merged