[OPENGL] Fix corrupted graphics.
scummvm/scummvm pull request #4155
Opened 2022-08-03 17:41 UTC by carlo-bramini

Size of the alpha channel is not set to its default value and this caused totally corrupted graphics on my PC.
See:
https://bugs.scummvm.org/ticket/13712

2022-08-03 18:59 UTC, aquadran commented
commit prefix is wrong

2022-08-03 19:00 UTC, aquadran requested changes
commit prefix is wrong

2022-08-03 19:14 UTC, carlo-bramini commented
> commit prefix is wrong

Excuse me, how should I change it?
Would "OPENGL: Fix corrupted graphics" be better?

2022-08-03 19:34 UTC, antoniou79 commented
> > commit prefix is wrong
> 
> Excuse me, how should I change it? Would "OPENGL: Fix corrupted graphics" be better?

It would be conforming to the format rules for the commit message, indeed.
You can have a look at the history of commits for the specifc file that is changed by this commit, to use the most appropriate prefix. 
https://github.com/scummvm/scummvm/commits/cd00fa6bdb740a567e5cdd70dba4bf218ed7851b/backends/graphics/openglsdl/openglsdl-graphics.cpp

In the history there are commits with "OPENGL: ", "SDL: ", "BACKENDS: OPENGLSDL" (I think I prefer this one as more appropriate), "OPENGLSDL: ".

2022-08-11 21:30 UTC, bluegr commented
This fixes the uninitialized variable. Since the commit message is correct now, it is good to be merged. Thanks!

2022-08-11 21:30 UTC, merged