AGI: Write log() Function to File
scummvm/scummvm pull request #4333
Opened 2022-10-14 02:27 UTC by zephyern

Now the log() function writes to a file, as
the AGI engine did.

It appears that ScummVM doesn't have any "append" functionality. As a result, I made this implementation create a new file each time a message is logged. Note that the file is only created if the log() function is called. The file name includes the game name and the current time, ensuring that logs won't be overwritten.

The format is: agi.<gameid>.<currentime>.log and will be logged to the working directory.

Last week I first implemented the log() function. In that commit I just had it log to the console. In this commit we start writing to a file.

2022-10-14 06:35 UTC, sev- requested changes
Thank you for working on it.

The logs themselves need to be put into a special directory and the target name is used for its name. This also will be consistent with the saves.

Are you sure you want to keep logs for every run?

In order to append, simply use `dumpFile .seek(dumpFile.size());` before writing to it.

2022-10-14 06:35 UTC, sev- commented on engines/agi/op_cmd.cpp
> +	return Common::String::format("agi.%s.%d%02d%02d%02d%02d%02d.log",
Please put it in the "dumps/" directory. The users will need to create that directory manually if the want to see the logs. That is a common practice in ScummVM.

2022-10-14 06:35 UTC, sev- commented on engines/agi/op_cmd.cpp
> +								  state->name,
It is better to use here `getTargetName()` because there could be more than one game with the same original name.

2022-10-14 06:35 UTC, sev- commented on engines/agi/op_cmd.cpp
> +		static Common::DumpFile dumpFile;
I am not a big fan of static objects like this. Why not move it to the `AgiEngine` class variable?

2022-10-14 12:06 UTC, zephyern commented
Thanks for your feedback! Super helpful. Your suggestions make sense. Will make the changes and resubmit this weekend.

2022-10-14 12:49 UTC, sev- commented
If you were not working with GitHub before, do not close this PR, just push (or force push) to the same branch and GitHub will pick it up as part of this PR.

2022-10-15 20:46 UTC, zephyern commented
Ok, I was able to resolve most of your comments.
1. I put the log into the `dumps` directory, and we only log to a file if that directory exists.
2. I exposed and used `getTargetName()` in the log file name.
3. Removed the static variable by putting the DumpFile in the `AgiEngine`. (I only initialize it in the `cmdLog()` method because I don't think many games will actually use log(). If you think I should always initialize it, happy to make that change.)

There were two comments which I didn't address, but would be happy to hear your thoughts and revisit:
1. Re: `dumpFile.seek(dumpFile.size());`. I actually tried this originally because I agree that appending to a single file would be the preferred behavior. The problem is that  `dumpFile.size()` returns `0` and the file is actually empty. The reason for this is that under the covers `Common::DumpFile` opens the file with the `"wb"` option which results in the file always being replaced. We'd need to open the file with `"ab"` in order to append. (See the [fopen](https://cplusplus.com/reference/cstdio/fopen/) docs.) I'm happy to expose an append-mode to `Common::DumpFile` and pipe it down through the stack, however I thought that may be a bit much to just support this feature. Let me know if you think this would be useful functionality for other parts of the system? See the underlying code behind `Common::DumpFile` here: https://github.com/scummvm/scummvm/blob/90f2ff2532ca71033b4393b9ce604c9b0e6cafa0/backends/fs/stdiostream.cpp#L123)
2. Re: writing timestamp. Because we're still creating a new file each time the game is started, and that filename contains the timestamp, I held off on this suggestion. If we append to the file, I think it's a good idea.

2022-10-16 19:52 UTC, sev- commented
Looks good, merging. Thank you!

2022-10-16 19:52 UTC, merged