DIRECTOR: Lingo fixes, add support for displaying 2-bit and 4-bit bitmaps
scummvm/scummvm pull request #4583
Opened 2023-01-01 11:47 UTC by moralrecordings

2023-01-01 19:49 UTC, sev- requested changes
Good stuff, but we have to make sure that D2-D3 is working. The release cycle is close and we should not break the supported games

2023-01-01 19:49 UTC, sev- commented on engines/director/castmember.cpp
> -		if (_bitsPerPixel == 1)
This needs to be tested with The Apartment

2023-01-01 19:49 UTC, sev- commented on engines/director/castmember.cpp
> +				// 1bpp - this is preconverted to 0x00 and 0xff, change nothing.
This not indented correctly: switch() does not add an indent level

2023-01-03 13:26 UTC, sev- commented on engines/director/graphics.cpp
> +		*dst = p->applyColor ? (~src | p->backColor) & (*dst | src) : *dst | src;
We have bunch of tests here: https://github.com/scummvm/director-tests/tree/master/D3-mac

You may consider checking them (and extending the test suite :) )

2023-01-09 06:39 UTC, moralrecordings commented
Oh my god I fell for the "pending" label again, thanks Github designers

2023-01-09 18:55 UTC, sev- commented
I'd love to merge it before the release, but it still breaks several movies on our buildbot. Do you plan to look into that?

2023-01-10 12:41 UTC, sev- commented
Thank you! Merging

2023-01-10 12:41 UTC, merged