GUI: In grid view show invalid entries in grey text and darken the thumbnail
scummvm/scummvm pull request #4696
Opened 2023-02-08 21:21 UTC by tag2015

Unlike the list view, currently the invalid entries are not indicated in any way.
This PR:
* Changes the color of the invalid entries to KFontColorAlternate (like the listview)
* Adds a simple svg overlay (which is just a 60% dark square) to darken the icon so that it looks "inactive"

The .svg is placed in /icons/extra/ but maybe another location would be better suited (suggestions welcome)

2023-02-08 21:22 UTC, tag2015 commented
Example:
![Capture2](https://user-images.githubusercontent.com/1673892/217653885-a7c3b8cc-fd2b-4ffe-a3bf-146ad93fb059.PNG)

2023-02-12 08:49 UTC, bluegr commented on gui/widgets/grid.cpp
> +const Graphics::ManagedSurface *GridWidget::disableThumbnail() {
```suggestion
const Graphics::ManagedSurface *GridWidget::disabledThumbnail() {
```

2023-02-12 08:52 UTC, bluegr commented
Nice work!
Regarding the overlay thumbnail, it would be best if it was placed together with the other common theme SVG files under [gui/themes/common-svg](https://github.com/scummvm/scummvm/tree/master/gui/themes/common-svg)

2023-02-14 17:21 UTC, tag2015 commented
> Nice work! Regarding the overlay thumbnail, it would be best if it was placed together with the other common theme SVG files under [gui/themes/common-svg](https://github.com/scummvm/scummvm/tree/master/gui/themes/common-svg)

Is there a way to load the SVG from that path or the best course of action would be updating and rebuilding the themes and then using theme()->getImageSurface ?

2023-03-05 20:22 UTC, sev- commented
My understanding is that this overlay is a simply gray color with transparency.

If it is the case, I think, you do not need a file at all, just create a surface and call `::fill()` on it

2023-03-07 11:17 UTC, tag2015 commented
> My understanding is that this overlay is a simply gray color with transparency.
> 
> If it is the case, I think, you do not need a file at all, just create a surface and call `::fill()` on it

Good point, done. I used a picture initially because I wasn't sure of the end result but it's simpler this way

2023-03-08 00:15 UTC, sev- requested changes
Couple small formatting issues

2023-03-08 00:15 UTC, sev- commented on gui/widgets/grid.cpp
> +		if(_disabledIconOverlay)
```suggestion
		if (_disabledIconOverlay)
```

2023-03-08 00:15 UTC, sev- commented on gui/widgets/grid.cpp
> +		gfx->fillRect(Common::Rect(0,0,_thumbnailWidth,_thumbnailHeight), disabledThumbnailColor);
```suggestion
		gfx->fillRect(Common::Rect(0, 0, _thumbnailWidth, _thumbnailHeight), disabledThumbnailColor);
```

2023-03-08 10:18 UTC, tag2015 commented on gui/widgets/grid.cpp
> +		if(_disabledIconOverlay)
Thanks, fixed!

2023-03-08 10:18 UTC, tag2015 commented on gui/widgets/grid.cpp
> +		gfx->fillRect(Common::Rect(0,0,_thumbnailWidth,_thumbnailHeight), disabledThumbnailColor);
Thanks, fixed!

2023-03-20 18:26 UTC, merged