VCRUISE: Only require MP3 and JPEG support for game versions that need it
scummvm/scummvm pull request #4732
Opened 2023-02-22 15:27 UTC by ccawley2011

2023-02-22 17:23 UTC, sev- commented on engines/vcruise/detection.h
> +	byte requirements;
Why don't you make game flags? E.g. stuff it in `desc.flags` ?

2023-02-23 02:30 UTC, elasota commented
I made a mistake with the initial report of this problem anyway: Schizm does not use MP3, it uses Vorbis.

2023-02-23 02:38 UTC, elasota requested changes

2023-02-23 02:38 UTC, elasota commented on engines/vcruise/vcruise.cpp
> +	if (_gameDescription->gameID & REQUIRES_JPEG) {
These are checking the gameID field instead of requirements

2023-02-24 23:39 UTC, elasota commented
Since pretty much everything in this needed some revision I just did it myself, equivalent changes are in as of f21ea7ba3e55f62c870600c21d5f918c423051f4

Closing this.

2023-02-24 23:39 UTC, closed without merging