SLUDGE: Add game to detection table.
scummvm/scummvm pull request #4883
Opened 2023-04-05 20:41 UTC by oknowpressspacetojump

2023-04-09 10:58 UTC, sev- requested changes
Please fix two little thing and change the commit log message to be specific, which game you added, like: "SLUDGE: Added detection for v 0.1 of outoforder"

By changing the commit, DO NOT CLOSE this PR. Rather just force-push and GitHub will pick it up.

2023-04-09 10:58 UTC, sev- commented on engines/sludge/detection_tables.h
> +			"",
Please specivy the version here

2023-04-09 10:58 UTC, sev- commented on engines/sludge/detection_tables.h
> +			Common::kPlatformUnknown,
Please set it to Windows

2023-04-09 20:54 UTC, oknowpressspacetojump reviewed
fixed. added version for the pervious entry as well

2023-05-14 20:48 UTC, sev- commented
Thanks!

2023-05-14 20:48 UTC, merged