ENGINE: fixes tinsel bug #9625
scummvm/scummvm pull request #5086
Opened 2023-06-11 10:27 UTC by solidrobo

Increases the soundreel pool to 10 from 5 and when running out overwrites the last one

By skipping many dialogue lines in a row it is easy to run out of soundreel slots by doubling the slots it's less likely to happen and by not raising an error when it happens the game will not crash if soundreel slots run out

2023-06-11 11:20 UTC, digitall commented
@solidrobo: Thanks for looking at this. One quick point, could you use rebase and change the  commit message to "TINSEL: Fix for Bug 9625 (Out of Sound Reels)", that is more descriptive and has the correct engine prefix.

2023-06-11 11:25 UTC, digitall commented
@solidrobo : While your fix will stop / avoid the sound reel bug, it will break save / loading of existing savegames and break compatibility. The sound reels are saved to the savestate files hence why this is hard to fix than just increasing the pool:
https://github.com/scummvm/scummvm/blob/master/engines/tinsel/saveload.cpp#L340

2023-06-11 11:27 UTC, digitall commented
A fix for that bug would require loading and correct function of the engine with existing savegames, while increasing the runtime sound reel pool and save state for new savegames. We do have precedent for this, but best to talk to @dreammaster about this...

2023-06-11 15:49 UTC, bluegr commented
I've changed the description of the pull request, please update the description of the commit accordingly.

This bug is triggered in a single scene, as there are more than 5 sound effects playing.

As @digitall said, this fix has two major issues which are not addressed:

- Existing saved games will be broken, because the sound reels are synced
- Changing the error into a warning will lead to invalid memory access

Please check the issues mentioned above

2023-08-06 12:31 UTC, sev- commented
@solidrobo any updates?

2023-08-06 14:54 UTC, bluegr requested changes
The issues identified above will need to be addressed. Otherwise, we should think of another way of addressing this bug, and close this PR

2023-08-06 23:02 UTC, dreammaster commented
Okay, I went ahead and did my own implementation that increases the soundreels to 10, and bumps up the savegame version to 4 so that new saves will use 10, but the old saves with only 5 still load okay.

2023-08-06 23:02 UTC, closed without merging