AGS: ARM Neon blending and blitting optimizations
scummvm/scummvm pull request #5144
Opened 2023-07-08 18:46 UTC by wyatt-radkiewicz

Wrote code in surface.cpp/surface.h which runs at least 4x better on
average by leveraging the ARM Neon SIMD extensions, and added
the base structure for future SSE2 optimizations.

Majority of the new code pertaining to the optimized blending/blitting
is in engines/ags/lib/allegro/surface_simd_neon.h and .cpp.

2023-07-15 22:01 UTC, tag2015 commented
Hi, may I ask which games you tested the SSE2 optimizations with? I built your PR on Win10 with an intel CPU and
found some issues (mostly segfaults, but also a couple problems with wrong colors)

2023-07-31 01:24 UTC, wyatt-radkiewicz commented
> Hi, may I ask which games you tested the SSE2 optimizations with? I built your PR on Win10 with an intel CPU and
> found some issues (mostly segfaults, but also a couple problems with wrong colors)

I tested it so far on Kings Quest 2 AGDI edition and Murder Cases Demo with Win10 and an intel CPU but haven't gotten any weird colors or segfaults. I'll fix this before GSOC, but currently I'm working on a different part of my GSOC project.

2023-07-31 17:38 UTC, tag2015 commented
> I tested it so far on Kings Quest 2 AGDI edition and Murder Cases Demo with Win10 and an intel CPU but haven't gotten any weird colors or segfaults. I'll fix this before GSOC, but currently I'm working on a different part of my GSOC project.

Ok, when you have time or taking a break from the other task it'd be nice if you could test something else such as the following demos:
https://store.steampowered.com/app/1346360/Old_Skies/
https://www.moddb.com/games/the-cat-lady/downloads/the-cat-lady-demo-free
http://www.screen7.co.uk/games/download/Downfall2016_Demo_1.0_Setup.exe
https://bestgames.itch.io/rock-n-roll-will-never-die

2023-08-06 20:21 UTC, sev- requested changes
Outstanding work!

I have only a few minuscule notes. Then it could be merged

2023-08-06 20:21 UTC, sev- commented on engines/ags/engine/main/engine.cpp
> +#include "ags/lib/allegro/color.h"
I think, this is a leftover from some early experiments

2023-08-06 20:21 UTC, sev- commented on engines/ags/globals.cpp
> +	__bitmap_simd_optimizations = checkForSIMDExtensions();
Why two underscores at the beginning?

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/allegro/surface_simd_neon.cpp
> +#include "ags/lib/allegro/surface_simd_neon.h"
The file is missing ScummVM copyright header

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/allegro/surface_simd_none.cpp
> +#include "ags/lib/allegro/surface.h"
Please add the copyright header

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/allegro/surface_simd_ppc.cpp
> +// TODO: Complete PowerPC code
Do we need this file at this moment?

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/allegro/surface_simd_neon.cpp
> +#include "common/textconsole.h"
Please move common/ and graphics/ includes before ags/ ones

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/allegro/surface_simd_ppc.h
> +/* ScummVM - Graphic Adventure Engine
Same thing. I think this file could be removed

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/allegro/surface_simd_sse.cpp
> +#include "ags/lib/allegro/surface_simd_sse.h"
Copyright header...

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/allegro/surface_simd_sse.cpp
> +#include "common/textconsole.h"
includes order...

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/allegro/surface_simd_sse.cpp
> +    __m128i tint = _mm_sll_epi32(_mm_set1_epi32(srcAlpha), _mm_set1_epi32(24));
Spaces sneaked in into indentation, and on line 39

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/allegro/surface_simd_sse.h
> +{
Code formatting

2023-08-06 20:21 UTC, sev- commented on engines/ags/lib/std/functional.h
> -	operator bool() const {
Why is this removed? This method does not alter the class, thus, `const`

2023-08-06 20:21 UTC, sev- commented on engines/ags/tests/test_gfx.cpp
> +												case kSourceAlphaBlender: debug("blenderMode: kSourceAlphaBlender"); break;
... we indent switch() statement differently. Please check our Code Formatting Conventions

2023-08-28 19:15 UTC, sev- commented
Thank you!

2023-08-28 19:16 UTC, merged