GUI: Create dialog to verify integrity of game files
scummvm/scummvm pull request #5247
Opened 2023-08-10 17:05 UTC by PhoenixFlame101

- Connect to API endpoint that processes POST requests, and compares submitted checksums against those in the database.
 - Button to initiate verification present in Game Options -> Paths
 - Results are displayed in a dialog, on a file-by-file basis

2023-08-11 13:12 UTC, sev- requested changes
Did my review. The dialog is not complete

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +	case kChecksumComplete: {
You do not need this set of curly braces

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +				debug("got here lol");
lol

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +				for (auto size : {0, 5000, 1024 * 1024}) {
for mac files, you need to compute:  r5000, m5000, d5000, rt5000, mt5000, dt5000 and r, d (full). No need to compute 1024 * 1024.

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +			fileChecksum.push_back(Common::computeStreamMD5AsString(file).c_str());
I wonder, how do you distinguish between all of these checksums in the array? I see you pushing just the checksums.

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +		long long fileSize = tempFile.size();
please use `uint64`, as in the prototype.

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +		Common::StringArray checkcodes = {"md5", "md5-5000", "md5-1M", "md5-t-5000"};
I do not see mach checksums here

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +	debug(r->stringify().c_str());
Please hide it to some debug level and add some prefix like "JSON response: "

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +	debug("ERROR %ld: %s", error.httpResponseCode, error.response.c_str());
it should be `warning()`

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +			Common::String::format("Your set of game files seems to be unknown to us. If you are sure that this is a valid unknown variant, please send the following e-mail to integrity@scummvm.org \n\
You must mar this string as translatable, e.g. wrap it in `_()`

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +		The details of the game : %s, %s, %s, %s, %s",
Where is the part asking to send an e-mail and copy all of this info to the clipboard?

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +		else if (status == "checksum_mismatch")
We need also report the actual names for the mismatched/missing/extra files

2023-08-11 13:12 UTC, sev- commented on gui/integrity-dialog.cpp
> +		messageText += "Files all OK";
This must be marked as translatable

2023-08-16 22:49 UTC, sev- commented on common/str.cpp
> +			c == '~' || c == '-' || c == '.' || c == '_')
Sigh. I was asking to enhance this!

2023-08-22 19:17 UTC, sev- commented on gui/integrity-dialog.cpp
> +#include "gui/integrity-dialog.h"
Always include common files before gui/

2023-08-23 20:20 UTC, bluegr commented on common/str.cpp
> +		if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') ||
You can use utility functions for these checks, found in common/util.h. e.g. check (`isAlNum()`)[https://github.com/scummvm/scummvm/blob/83b3d3a91bd2267e4601aee62e1d244f9a571f6d/common/util.h#L267]

2023-08-23 20:24 UTC, bluegr commented on response.json
> +{
This file shouldn't be in-tree. It should be added to .gitignore, too

2023-08-23 20:26 UTC, bluegr commented on gui/integrity-dialog.cpp
> +		"Verifying file integrity may take a long time to complete. Please wait...\n");
```suggestion
		"Verifying file integrity. This may take a long time to complete. Please wait...\n");
```

2023-08-23 20:31 UTC, bluegr commented on gui/integrity-dialog.cpp
> +				auto fileStream = originalStream;
Why do you need originalStream then? Just use fileStream directly

2023-11-09 20:05 UTC, sev- commented
@coderabbitai review

2024-06-13 23:24 UTC, sev- commented
This was manually merged and all commits checked for compliability

2024-06-13 23:24 UTC, closed without merging