SCUMM: Colorize box debug rendering; debug draw objects like boxes
scummvm/scummvm pull request #5277
Opened 2023-08-18 14:29 UTC by manabreak

Draw boxes in scumm debugger with different colors to make them easier to separate visually. Also, draw object rectangles with different colors. See attached screenshots.

![color_boxes](https://github.com/scummvm/scummvm/assets/3799319/c0c0f644-91b9-44ff-97f4-410d525ff124)
![color_objects](https://github.com/scummvm/scummvm/assets/3799319/2c74e09f-a235-4cd8-b22a-9f0f84a8e8fb)

2023-08-18 14:33 UTC, AndywinXp commented
Hey! Glad you could open a PR for this one 😄 It looks good to me! Let's leave it open for tests for a few days and then we can merge it; this looks extremely useful for speedrunners!

2023-08-19 03:48 UTC, manabreak commented
Actually, now that I fiddled around with this, it might benefit from an extra option to toggle between multicolor and single color views. The multicolor one seems to be dependent on the active palette, and as such, it sometimes produces results that are quite difficult to see, especially when trying to view the dotted walkboxes.

2023-08-21 17:02 UTC, AndywinXp commented
> Actually, now that I fiddled around with this, it might benefit from an extra option to toggle between multicolor and single color views. The multicolor one seems to be dependent on the active palette, and as such, it sometimes produces results that are quite difficult to see, especially when trying to view the dotted walkboxes.

As you prefer! 🙂 If you feel that this PR still needs some work, mark it as draft and/or add [WIP] at the beginning of the PR title, so it doesn't get accidentally merged by someone.

2023-08-28 20:24 UTC, sev- requested changes
Yes, good stuff, and indeed, implement a toggle in the debugger for the single-color version.

I think the easiest way will be to make `getNextColor()` return a constant in this mode, then the overall code will not need any checks.

2023-08-28 20:24 UTC, sev- commented on engines/scumm/debugger.h
> +	static const int DEBUG_COLOR_COUNT = 32;
Please move it to an `enum` or `#define`

2023-11-05 21:04 UTC, sev- commented
@manabreak any updates?

2023-11-06 03:42 UTC, manabreak commented
Sorry, I've had so much going on in my life lately, and can't really say when I have time to get back to this. Feel free to close this ticket.

LähetettyOutlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Eugene Sandulenko ***@***.***>
Sent: Sunday, November 5, 2023 11:04:33 PM
To: scummvm/scummvm ***@***.***>
Cc: Harri Pellikka ***@***.***>; Mention ***@***.***>
Subject: Re: [scummvm/scummvm] SCUMM: Colorize box debug rendering; debug draw objects like boxes (PR #5277)


@manabreak<https://github.com/manabreak> any updates?

—
Reply to this email directly, view it on GitHub<https://github.com/scummvm/scummvm/pull/5277#issuecomment-1793845309>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA47SF7QNM4X7HCJV2V3EODYC75ODAVCNFSM6AAAAAA3VTSOP6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJTHA2DKMZQHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-06 16:06 UTC, AndywinXp commented
I could pick it up later, this seemed useful enough to me.

2023-12-26 20:12 UTC, AndywinXp commented
I cherrypicked the commit and made the necessary change suggested by sev! We can close this, thanks for your work! 😄

2023-12-26 20:12 UTC, closed without merging