GOB: added new variants of Adiboud'chou to detection tables
scummvm/scummvm pull request #5282
Opened 2023-08-22 13:52 UTC by BJNFNE

2023-08-27 12:18 UTC, sdelamarre commented
Thank you!

2023-08-27 12:20 UTC, sdelamarre requested changes

2023-08-27 12:20 UTC, sdelamarre commented on engines/gob/detection/tables_adiboudchou.h
> +
Useless blank line

2023-08-27 12:20 UTC, sdelamarre commented on engines/gob/detection/tables_adiboudchou.h
> +
Useless blank line

2023-08-27 12:23 UTC, sdelamarre commented
Can you remove the two spotted useless blank lines, and also the one at line 48 (adiboudchoubanquise) introduced in your last commit?

2023-08-27 13:33 UTC, BJNFNE commented
I think i messed this one up, i am no longer able to merge / squash the commits anymore, i begin from scratch with a new PR

2023-08-28 16:24 UTC, merged

2023-08-28 16:24 UTC, sdelamarre commented
Squashed, thank you.