CRAB: Enable TTS in Crab Engine
scummvm/scummvm pull request #5457
Opened 2023-11-21 18:01 UTC by Brakkugit

2023-11-21 18:50 UTC, sev- requested changes
added two minor notes

2023-11-21 18:50 UTC, sev- commented on engines/crab/ui/ChapterIntro.cpp
> +#include "common/text-to-speech.h"
why is it here?

2023-11-21 18:50 UTC, sev- commented on engines/crab/ui/ChapterIntro.h
> +
please revert this line change

2023-11-22 11:14 UTC, sluicebox commented
Also: this doesn't build! =)

See the red X for details

2023-11-24 06:04 UTC, merged