TINYGL: Remove unimplemented OpenGL 1.2 declarations
scummvm/scummvm pull request #5520
Opened 2023-12-12 20:58 UTC by ccawley2011

This makes it a bit easier to identify where fallbacks might be needed in equivalent OpenGL code, and makes it slighly clearer what TinyGL actually supports.

`TGL_BGR` and `TGL_BGRA` were being used by the HPL1 engine, but my understanding is that TinyGL support there is still incomplete so I just commented the relevant code out.

2023-12-12 21:06 UTC, aquadran requested changes
I prefer code commented not removed

2023-12-12 21:09 UTC, aquadran commented on engines/hpl1/engine/impl/low_level_graphics_tgl.cpp
> +#if 0
I'm not sure bout, all texture modes inside implementations are supported

2023-12-12 21:13 UTC, aquadran commented
there are few cases in 1.1 which were declared and never implemented. to have header easier to maintain I prefer to keep as it is. it's up to developer to check implementation status for engine. I'm rather agains it doing any changes in header.

2025-04-30 11:02 UTC, sev- commented
@ccawley2011 any update?

2025-09-01 20:01 UTC, bluegr commented
The bulk of the changes in this PR modify the TinyGL header file, which is not desired. The changes in the TinyGL .cpp files are not applicable if the header is left unchanged.
Regarding the rest of the changes, the ones in the HPL engine are mostly invalid, since they remove code that is actually implemented.

Thus, the overall changes in this PR are not desired and since there's no further response from @ccawley2011 on @aquadran's feedback, I'm closing this.

2025-09-01 20:01 UTC, closed without merging