BACKENDS: MIDI: Improvements to automatic device detection, synth support for OSS
scummvm/scummvm pull request #5622
Opened 2024-01-14 17:23 UTC by elasota

This adds a few things:
- Support for `checkDevice` to FluidSynth, along with a check flag that allows an engine to signal that it will supply a sound font (so dragons engine doesn't fail)
- Quiet mode to `checkDevice`
- Proper device enumeration for OSS
- OSS synth device support

2024-01-20 22:32 UTC, sev- requested changes
Looks mostly good, but have several notes. Thank you for looking into this!

2024-01-20 22:32 UTC, sev- commented on audio/softsynth/fluidsynth.cpp
> +	int statResult = stat(fsPath.c_str(), &st);
You cannot use this in a non-backend code. Does `FSNode::isDirectory()`  not work for you?

2024-01-20 22:32 UTC, sev- commented on audio/mididrv.h
> +	static bool checkDevice(DeviceHandle handle, int flags, bool quiet);
Could you please add doxygen documentation, explaining these parameters?

2024-01-20 22:32 UTC, sev- commented on audio/musicplugin.h
> +	virtual bool checkDevice(MidiDriver::DeviceHandle hdl, int flags, bool quiet) const { return true; }
Same here, documentation has to be updated

2024-01-20 22:32 UTC, sev- commented on audio/softsynth/fluidsynth.cpp
> +#include <sys/stat.h>
Big no. See below.

2024-01-21 03:46 UTC, elasota commented
The `stat` call is due to FluidSynth using `fopen` directly unless it is compiled to use stream callbacks (which right now it only does on Android).  Unfortunately, `FSNode::exists` does some path manipulation that makes it subtlely different from `fopen`, e.g. on Windows, `fopen` uses the system code page but `FSNode::exists` uses UTF-8.

I can add an extra call to the backend to deal with this, but the problem is that if we really want to robustly tell if `fopen` will succeed, we need to use a call that resolves the path we feed to FluidSynth the same way that `fopen` would, without any manipulation.

2024-01-21 10:11 UTC, lephilousophe commented
A call to `access` would be better as it also checks for rights of current user.

2024-07-03 09:45 UTC, bluegr commented
What is the status of this PR @elasota?

2024-07-03 18:53 UTC, elasota commented
> What is the status of this PR @elasota?

I updated the PR to just use `FSNode::exists`.  As far as I can tell, this only matters for FluidSynth 1.x, which per discussion seems to only be used on Ubuntu Bionic and the precompiled VS libraries.  I don't think it matters for the former, and the latter case isn't being used by our release builds, and I think the better solution there is to update the precompiled libraries to 2.x

2024-11-04 09:06 UTC, bluegr commented
Thanks @elasota, so there is no actual impact (plus, Ubuntu Bionic is now 6 years old).

Will this also help addressing this bug?
https://bugs.scummvm.org/ticket/14793

2024-11-04 11:35 UTC, bluegr commented
Related bug: https://bugs.scummvm.org/ticket/11715

2024-11-04 21:00 UTC, bluegr commented
Thanks for your work! This can be merged, after the discussion we had on Discord. It fixes bug 11715

2024-11-04 21:00 UTC, merged