DUMPER: Add feature to extract data from ISO9660 and hybrid disk images
scummvm/scummvm pull request #5679
Opened 2024-03-01 20:27 UTC by Darkhood148

2024-03-07 20:38 UTC, rvanlaar requested changes
Code itself looks alright.

Improve your commit messages by reviewing our commit guidelines: https://wiki.scummvm.org/index.php/Commit_Guidelines 
Also read the commit log for the dumpercompanion for a general feeling what's expected.

What's the reason behind a parser_hfs, parser_iso9660 and parser_hybrid?
The answer to this question should have been clear from the commit messages.

2024-03-07 20:38 UTC, rvanlaar commented on devtools/dumper-companion.py
> +import pycdlib
Update the documentation at the top of the file. 
Specifically add `pycdlib` to the prerequisites line.

2024-03-08 21:09 UTC, Darkhood148 commented
@rvanlaar I have changed the commit messages and added pycdlib to the prerequisites line. Can you review it please?

2024-03-18 09:42 UTC, einstein95 commented on devtools/dumper-companion.py
> +        # print(upath)
Could this be changed to an "if not silent: print(upath)"? Otherwise nothing is printed if not in silent mode

2024-04-09 15:08 UTC, rvanlaar commented
For the latest commit, the version check. I'm missing important information. Something along the lines of:

- library doesn't implement encoding parameter.
- link to PR
- code can be removed when PR is merged

2024-04-11 20:50 UTC, Darkhood148 commented
@rvanlaar I have made the changes.

2024-04-16 17:50 UTC, rvanlaar commented
The changes look good. Will need to test it though with a mac and regular iso.

For the future: think about how python types could have helped:
`ExtensionTypes = Literal["udf", "joliet", "udf"]

2024-04-24 22:28 UTC, sev- commented
Thank you, merging

2024-04-24 22:28 UTC, merged