GRIM: Revert removal of W/A for nil in luaD_call (Bug #14987)
scummvm/scummvm pull request #5692
Opened 2024-03-04 23:36 UTC by somaen

Original removal in 2c997d175cbc1b9a6ff0c5a1bb58bb4bc7776c00

Without this W/A we get stuck after opening the security door, see bug #14987.

This W/A does not resolve the issue with the walk cycle getting stuck.

2024-03-05 04:37 UTC, aquadran requested changes
no wa for main

2024-03-05 06:51 UTC, somaen commented
I disagree in this case: We should indeed fix this issue in the scripts properly, BUT without the WA all existing savegames will be incompletable. If the fix ends up being a script patch then that won’t be picked up by existing save games.

So I would suggest reintroducing this WA until we have a proper fix, so the game is completable, and then consider whether we can remove it at all based on what the proper fix was.

2024-03-05 07:16 UTC, AndywinXp commented
I agree, being that we're nearing a bugfix release and that the game (which is a flagship title ) is currently not completable, this workaround is a necessity for the time being.

2024-03-07 13:08 UTC, closed without merging

2024-03-07 13:55 UTC, DjDiabolik commented
So it's this point passed whit current daily build or need a proper fix ?

2024-03-07 15:54 UTC, sev- commented
it is absolutely unclear, what happened with this Pull Request.

The reality is that it was pushed to branch-2-8. I wonder, what about the `master`?

2024-03-07 17:27 UTC, DjDiabolik commented
> it is absolutely unclear, what happened with this Pull Request.
> 
> The reality is that it was pushed to branch-2-8. I wonder, what about the `master`?

mmmmmm..... it's problably pushed on future 2.8 .... problably it's pushed here:
![immagine](https://github.com/scummvm/scummvm/assets/9040397/2309fa3c-a66b-46d9-9dde-a325c0b67ea1)

It's be different between future 2.8 and daily build master brach... problably

2024-03-08 12:52 UTC, DjDiabolik commented
@aquadran from Buildbot it's correct You stay to tray to compile the current brach-2.8 whit this commit and it's fail ?

Or how i can download this build ? In my case i can try it on Windows x64 but, at my home, i also have a Ubuntu 22.04.4 LTS Mini PC whit scummvm ready-to-use.
I can try myself to compile this branch of scummvm ?

2024-10-01 04:04 UTC, paul19920801 commented
and update on this running 2.9.0  and having the same issue. So annoying. All I want to do is to finish Grim Fandango Running Ubuntu 24.04 & Scrumm 2.9.0

2024-10-01 15:36 UTC, AndywinXp commented
Seriously, if the parts opposing to merging this on master are not going to work on the Grim Fandango engine anytime soon it's best to merge this and mark it as a `HACK` with a comment like it is done on engines like SCUMM. When time will come, people will pick it up and fix it properly, just like it has happened on SCUMM in the last four years. 

Until then the game must stay in a non-broken state...

2024-10-01 15:46 UTC, DjDiabolik commented
@paul19920801 and @AndywinXp you have to use the "ScummVM stable Future 2.8.x" from buildbot..... only this master branch have the fix for pass this BUG with the Security Door.

2024-10-01 15:47 UTC, AndywinXp commented
I know, I'm on the developer team :P that's why I'm manifesting my discomfort for the decision taken above

2024-10-13 18:32 UTC, lephilousophe commented
This is now fixed by commit 7e34e793f973b6b8bf50b5a4a9dbf2552c8124b2.
The existing saves are still broken as they embed the bogus code in them, though.
Starting from a new game works.

2024-10-14 09:38 UTC, DjDiabolik commented
> This is now fixed by commit [7e34e79](https://github.com/scummvm/scummvm/commit/7e34e793f973b6b8bf50b5a4a9dbf2552c8124b2). The existing saves are still broken as they embed the bogus code in them, though. Starting from a new game works.

@lephilousophe 
Wait wait... i have download the current "master" from buildbot..... So for pass this point on front of "Security Door" i really need to restart all games from beginning ? OMG :) 
So i can try to load a previous point savegame like in previous "years" of the games and reach same point ?

And from right now also the branch "Future Stable" have this need to restart the games from beginning ?

2024-10-15 19:24 UTC, lephilousophe commented
This is now fixed with commit 8cc72754d7ebd358067f8c1fd1e2fedda53909bc.

2024-10-25 15:09 UTC, DjDiabolik commented
> This is now fixed with commit [8cc7275](https://github.com/scummvm/scummvm/commit/8cc72754d7ebd358067f8c1fd1e2fedda53909bc).

wait... so from this commit i can restart from previus savegames ? if yes thanks for this news.. :)

2024-10-25 15:11 UTC, lephilousophe commented
Indeed

2024-10-25 15:19 UTC, DjDiabolik commented
@lephilousophe YES... i confirm... now the games it's finally concluded with all animation correctly... thanks for this.