HUGO: Add keymapper support
scummvm/scummvm pull request #5865
Opened 2024-06-22 17:24 UTC by NabeelShabbir

2024-06-22 17:47 UTC, OMGPizzaGuy commented on engines/hugo/metaengine.cpp
> +	Keymap *engineKeyMap = new Keymap(Keymap::kKeymapTypeGame, "made-main", "MADE main");
Copy / paste from "MADE"

2024-06-22 18:09 UTC, OMGPizzaGuy commented
For directional movement, does this handle holding two keys (e.g. up and left) nicely? If not, it might be out of scope as it probably would not previously, but would be a improvement if possible

2024-06-23 13:48 UTC, bluegr commented
Thanks for your work!
Although the changes here are simpler compared to the ones for SAGA, could you also split your changes here into smaller commits?

2024-06-23 14:03 UTC, NabeelShabbir commented
> Thanks for your work! Although the changes here are simpler compared to the ones for SAGA, could you also split your changes here into smaller commits?

Understood :saluting_face: :saluting_face:

2024-06-25 03:56 UTC, OMGPizzaGuy requested changes

2024-06-25 03:56 UTC, OMGPizzaGuy commented on engines/hugo/route.cpp
> +	case kActionMoveTop:
For this function, can keyCode be renamed to avoid confusion? Although it is an action, I'm inclined to suggest direction to match Route::setWalk

2024-06-25 12:25 UTC, OMGPizzaGuy approved these changes

2024-06-30 14:00 UTC, ccawley2011 commented on engines/hugo/hugo.cpp
> +				_parser->keyHandler(event);
Maybe this should be split into two functions?

2024-07-01 18:59 UTC, bluegr commented
Nice work, thanks!

2024-07-01 18:59 UTC, merged

2025-12-21 02:20 UTC, sluicebox commented
This broke *click to walk*, and now it's been broken for 18 months.

2025-12-21 18:25 UTC, OMGPizzaGuy commented
> This broke _click to walk_, and now it's been broken for 18 months.

I see there's a couple problems with direction needing to be set to the value of KEYCODES. Seems the best move is to update values of HUGOAction enum to be equal to those values. I'm working on a fix and I'm sad I didn't catch this earlier.

We should add a bug for this to track

2025-12-21 18:59 UTC, OMGPizzaGuy commented
Added bug here: https://bugs.scummvm.org/ticket/16403