TINSEL: Add keymapper support
scummvm/scummvm pull request #6016
Opened 2024-08-06 16:29 UTC by NabeelShabbir

2024-08-08 02:08 UTC, OMGPizzaGuy commented on engines/tinsel/metaengine.cpp
> +	act = new Action("ACTION", _("Action"));
Action Action! I think this could use a I18N comment to clarify it's use

2024-08-08 02:12 UTC, OMGPizzaGuy commented on engines/tinsel/tinsel.cpp
> +#ifdef SLOW_RINCE_DOWN case '>':
Missing newline here

2024-08-31 19:00 UTC, OMGPizzaGuy requested changes

2024-08-31 19:28 UTC, bluegr commented on engines/tinsel/metaengine.cpp
> +	act->addDefaultInputMapping("Right");
This can be resolved easily through the github interface
```suggestion
	act->addDefaultInputMapping("RIGHT");
```

2024-08-31 19:29 UTC, bluegr commented
Thanks! Looks good :) Squashing (for the fix done via github)

2024-08-31 19:29 UTC, merged