BACKENDS: Add SDL3 backend + update imgui
scummvm/scummvm pull request #6312
Opened 2024-12-14 16:34 UTC by scemino

This PR modifies the current SDL backend to add SDL3 support.
There are a lot of combinations so don't hesitate to read it carefully and/or test it.
I didn't test the SDL3_net library.
This is the first time I modify the configure file, so have a look and tell me if I need to do some changes (I'm sure you will ;)).
And maybe the way I handled all the `#ifdef` are not at your taste, so feel free to give some advice.

To do this PR I used these recommendations: https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md and of course https://wiki.libsdl.org/SDL3/CategoryAPI

2024-12-15 17:57 UTC, ccawley2011 commented
Since there are a lot of repeated `ifdef`s relates to functions that have simply been renamed or only have minor changes to the parameters, I'd recommend using wrapper functions where possible to make the changes easier to read and less fragile to maintain.

2024-12-15 19:15 UTC, scemino commented
> Since there are a lot of repeated `ifdef`s relates to functions that have simply been renamed or only have minor changes to the parameters, I'd recommend using wrapper functions where possible to make the changes easier to read and less fragile to maintain.

Thanks for your advice.
Do you prefer `#define`, static functions or member functions?

Here is an example with static functions:

Before:
```c
#if SDL_VERSION_ATLEAST(3, 0, 0)
    if (!SDL_AddGamepadMappingsFromFile(file.getPath().toString(Common::Path::kNativeSeparator).c_str()))
#else
    if (SDL_GameControllerAddMappingsFromFile(file.getPath().toString(Common::Path::kNativeSeparator).c_str()) < 0)
        error("File %s not valid: %s", file.getPath().toString(Common::Path::kNativeSeparator).c_str(), SDL_GetError());
#endif
```

After with static functions:
```c
static bool GameControllerAddMappingsFromFile(const char *file) {
#if SDL_VERSION_ATLEAST(3, 0, 0)
	return SDL_AddGamepadMappingsFromFile(file);
#else
	return SDL_GameControllerAddMappingsFromFile(file) >= 0;
#endif
}

...

if (!GameControllerAddMappingsFromFile(file.getPath().toString(Common::Path::kNativeSeparator).c_str()))
        error("File %s not valid: %s", file.getPath().toString(Common::Path::kNativeSeparator).c_str(), SDL_GetError());
    
```

2024-12-15 22:23 UTC, sev- commented
Regarding the imgui update, did you add the files from the matching git commit as rest of the code?

2024-12-16 19:26 UTC, scemino commented
> Regarding the imgui update, did you add the files from the matching git commit as rest of the code?

Yes I used the commit https://github.com/ocornut/imgui/commit/cb16568fca5297512ff6a8f3b877f461c4323fbe corresponding to the tag https://github.com/ocornut/imgui/releases/tag/v1.91.3

About this, I see that there is a `backends/imgui/scummvm.patch` file, I should update this file too, no?

2024-12-16 23:41 UTC, sev- commented
> About this, I see that there is a `backends/imgui/scummvm.patch` file, I should update this file too, no?
Yes. I use it for updating imgui from time to time. Just make a diff against the imgui git commit.

2024-12-17 20:42 UTC, scemino commented
> > About this, I see that there is a `backends/imgui/scummvm.patch` file, I should update this file too, no?
> > Yes. I use it for updating imgui from time to time. Just make a diff against the imgui git commit.

I updated the patch file, but I have a lot more changes than the previous one, can you have a look @sev- please?

2024-12-18 00:50 UTC, bluegr commented
> > Since there are a lot of repeated `ifdef`s relates to functions that have simply been renamed or only have minor changes to the parameters, I'd recommend using wrapper functions where possible to make the changes easier to read and less fragile to maintain.
> 
> Tell me if it's OK now or did you think something different?

There is no definite answer here... use whatever makes the code easier to read and maintain.

From the three options you provided:
- static wrapper functions would be a very straightforward way
- defines are a bit uglier than function wrappers, IMHO
- member functions are also a nice idea, we could keep all of these functions neatly placed inside classes, and instantiate a different class per SDL version

So, from the options above, we could either use a C-style implementation (static wrapper functions) or a C++-style implementation (different class per SDL version, inherited from a common parent class, with member functions). I personally like the C++ approach better, but function wrappers would also work just fine :)

2024-12-18 05:57 UTC, scemino commented
> > > Since there are a lot of repeated `ifdef`s relates to functions that have simply been renamed or only have minor changes to the parameters, I'd recommend using wrapper functions where possible to make the changes easier to read and less fragile to maintain.
> > 
> > 
> > Tell me if it's OK now or did you think something different?
> 
> There is no definite answer here... use whatever makes the code easier to read and maintain.
> 
> From the three options you provided:
> 
> * static wrapper functions would be a very straightforward way
> * defines are a bit uglier than function wrappers, IMHO
> * member functions are also a nice idea, we could keep all of these functions neatly placed inside classes, and instantiate a different class per SDL version
> 
> So, from the options above, we could either use a C-style implementation (static wrapper functions) or a C++-style implementation (different class per SDL version, inherited from a common parent class, with member functions). I personally like the C++ approach better, but function wrappers would also work just fine :)

I made my choice already, sorry I'm not a huge fan of inheritance and I don't see the benefit of creating 1 class by version.

2024-12-19 00:39 UTC, bluegr commented
> I made my choice already, sorry I'm not a huge fan of inheritance and I don't see the benefit of creating 1 class by version.

That's fine :) Nice implementation!

2024-12-26 08:50 UTC, lotharsm commented
Thank you for looking into this!

I wanted to give it a try on Mingw64, and currently it seems that Win32 isn't fully supported yet:
```
In file included from backends/platform/sdl/win32/win32-window.cpp:27:
./backends/platform/sdl/win32/win32-window.h:32:9: error: 'HWND' does not name a type
   32 |         HWND getHwnd();
      |         ^~~~
backends/platform/sdl/win32/win32-main.cpp: In function 'int WinMain(HINSTANCE, HINSTANCE, LPSTR, int)':
backends/platform/sdl/win32/win32-main.cpp:54:16: error: 'main' was not declared in this scope
   54 |         return main(__argc, __argv);
      |                ^~~~
make: *** [Makefile.common:176: backends/platform/sdl/win32/win32-main.o] Error 1
make: *** Waiting for unfinished jobs....
    C++      engines/scumm/boxes.o
    C++      engines/scumm/camera.o
backends/platform/sdl/win32/win32-window.cpp: In member function 'virtual void SdlWindow_Win32::setupIcon()':
backends/platform/sdl/win32/win32-window.cpp:36:29: error: 'getHwnd' was not declared in this scope; did you mean 'getwc'?
   36 |                 HWND hwnd = getHwnd();
      |                             ^~~~~~~
      |                             getwc
backends/platform/sdl/win32/win32-window.cpp: At global scope:
backends/platform/sdl/win32/win32-window.cpp:53:6: error: no declaration matches 'HWND__* SdlWindow_Win32::getHwnd()'
   53 | HWND SdlWindow_Win32::getHwnd() {
      |      ^~~~~~~~~~~~~~~
backends/platform/sdl/win32/win32-window.cpp:53:6: note: no functions named 'HWND__* SdlWindow_Win32::getHwnd()'
./backends/platform/sdl/win32/win32-window.h:29:7: note: 'class SdlWindow_Win32' defined here
   29 | class SdlWindow_Win32 final : public SdlWindow {
      |       ^~~~~~~~~~~~~~~
make: *** [Makefile.common:176: backends/platform/sdl/win32/win32-window.o] Error 1

```
I quickly went through the release notes and indeed it looks like `backends/platform/sdl/win32/win32-window.cpp` is missing something - I'll check if I can adapt it from the other changes.

2024-12-26 12:07 UTC, scemino commented
> I quickly went through the release notes and indeed it looks like `backends/platform/sdl/win32/win32-window.cpp` is missing something - I'll check if I can adapt it from the other changes.

That's nice of you, thank you.

2024-12-27 00:10 UTC, sev- requested changes
Colossal work, thank you!

Have number of comments, mainly on formatting and suggestion to add more wrappers.

I am concerned that the code now becomes much harder to maintain with this amount of `ifdefs`, so maybe splitting files/adding more wrappers could make it easier to read and less fragile?

2024-12-27 00:10 UTC, sev- commented on backends/platform/sdl/sdl-window.cpp
> +    	SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_Y_NUMBER, _lastY);
indentation

2024-12-27 00:10 UTC, sev- commented on backends/platform/sdl/sdl-window.cpp
> +			if(!SDL_SetWindowFullscreenMode(_window, NULL))
```suggestion
			if (!SDL_SetWindowFullscreenMode(_window, NULL))
```
and below

2024-12-27 00:10 UTC, sev- commented on backends/platform/sdl/sdl.cpp
> +	#include <SDL3/SDL_clipboard.h>
```suggestion
#include <SDL3/SDL_clipboard.h>
```
and below

2024-12-27 00:10 UTC, sev- commented on configure
> -_sdlconfig=sdl2-config
So, you're suggesting making SDL3 as a default?

2024-12-27 00:10 UTC, sev- commented on configure
> +cat > $TMPC << EOF
Indentation

2024-12-30 12:42 UTC, scemino commented
> Colossal work, thank you!
> 
> Have number of comments, mainly on formatting and suggestion to add more wrappers.
> 
> I am concerned that the code now becomes much harder to maintain with this amount of `ifdefs`, so maybe splitting files/adding more wrappers could make it easier to read and less fragile?

Sorry I've been sick for a few days, as soon as I feel better I'll take care of it.

2025-01-02 17:35 UTC, scemino commented on backends/graphics/openglsdl/openglsdl-graphics.cpp
> +	if (!SDL_GL_SetSwapInterval(_vsync ? 1 : 0)) {
No, it means you have good eyes.

2025-01-02 17:36 UTC, scemino commented on backends/events/sdl/sdl-events.cpp
> +#if SDL_VERSION_ATLEAST(3, 0, 0)
Is this what you had in mind?

2025-01-24 22:40 UTC, sev- commented
@scemino for generating patch, please use the same command as outlined in cff87d8c2e98b16f2669c54445f65240d23ecc9f

```bash
diff -rbu . ../scummvm/scummvm/backends/imgui/|grep -v ^Only >../scummvm/scummvm/backends/imgui/scummvm.patch
```

This will remove those whitespace and file path changes.

2025-01-24 23:11 UTC, sev- requested changes
It is much cleaner now, thank you for the split of `sdl-events.cpp` file.

My recommendation to add a `configure` key `--use-sdl3`, so then you give preference/try to it, otherwise, put it at the end of the detection list until we perform a thorough testing.

I like the `sdl-events.cpp` splut, the code looks much much cleaner, though, of course, somebody has to modify it in three places if any enhancements are added (relatively unlikely).

I wonder, does it make sense to do`[sdl-graphics.cpp` file? or it will be way too much?

I left a few small comments here and there, mostly on the formatting. as the code is pretty clean.

Also, did you test the backend with `testbed`? And also, perhaps `testbed` needs to be enhanced with test for the multifinger taps?

2025-01-24 23:11 UTC, sev- commented on backends/graphics/surfacesdl/surfacesdl-graphics.cpp
> +		if(!SDL_SyncWindow(_window->getSDLWindow()))
```suggestion
		if (!SDL_SyncWindow(_window->getSDLWindow()))
```

2025-01-24 23:11 UTC, sev- commented on backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
> +static bool sdlSetSwapInterval(int interval) {
I think, similar wrapper could be done for `LockScreen()` call

2025-01-24 23:11 UTC, sev- commented on configure
> + _sdlconfig=sdl2-config
```suggestion
_sdlconfig=sdl2-config
```
so, in essence, this change is gone

2025-01-24 23:11 UTC, sev- commented on configure
> +	if test "$_pkg_config" = "yes" && $_pkgconfig --exists sdl3; then
At this moment in time, I'd still put SDL3 as the latest option, e.g. SDL2 -> SDL1 -> SDL3, so it for sure does not break ports before the backend is thoroughly tested.

2025-01-24 23:11 UTC, sev- commented on configure
> +
revert?

2025-01-24 23:11 UTC, sev- commented on configure
> +#include "SDL3/SDL_net.h"
Similar thing, I recommend putting SDL3 down the detection list, so it will require special `configure` command line option

2025-01-25 12:51 UTC, ccawley2011 commented
> I like the `sdl-events.cpp` splut, the code looks much much cleaner, though, of course, somebody has to modify it in three places if any enhancements are added (relatively unlikely).

I feel that the code is less clean after the split because of the amount of duplication that could be avoided by simply using defines for the renamed functions, similarly to what we did when we first moved to SDL2 in commit  8530997fff7b5b9d558f7dd6a0d07c236e4de16f.

2025-01-25 15:49 UTC, scemino commented on backends/events/sdl/sdl3-events.cpp
> +	switch (key) {
Between sdl2/3 there is not a lot of changes: the name of the enums have changed, ex: KMOD_CTRL => SDL_KMOD_CTRL, but for sdl1/2, there is a lot:
![Screenshot 2025-01-25 at 16 47 43](https://github.com/user-attachments/assets/aaadf9a9-a41f-4f3c-b388-f839a37df1e0)

2025-01-25 19:08 UTC, scemino commented on backends/events/sdl/sdl3-events.cpp
> +			_touchPanels[port]._hiresDX += (event->tfinger.dx * 1.25 * speedFactor * xMax * FINGER_SUBPIXEL_MULTIPLIER);
Maybe you're right, but I don't feel I'm the best person to do it, I don't even know what it means.

2025-01-25 19:08 UTC, scemino commented on backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
> +static bool sdlSetSwapInterval(int interval) {
Sorry I don't get it.

2025-01-25 19:10 UTC, scemino commented on backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
> +static bool sdlSetSwapInterval(int interval) {
Sorry I don't get it.

2025-01-25 21:44 UTC, sev- commented on backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
> +static bool sdlSetSwapInterval(int interval) {
in `surfacesdl-graphics.cpp` file there are number of calls like this:
```C++
#if SDL_VERSION_ATLEAST(3, 0, 0)
	if (!SDL_LockSurface(_screen))
#else
	if (SDL_LockSurface(_screen) == -1)
#endif
```
My suggestion is to have a similar wrapper for the `LockSurface()` method, so there are less ifdefs

2025-01-26 19:30 UTC, scemino commented
> Also, did you test the backend with `testbed`?

I need to do the test with SDL1, then SDL2, then SDL3, right ?
That's a good idea, I found some bugs already with SDL3: `SDL_BlitSurface failed: The surface is not indexed format!`
I will fix this ASAP.

> And also, perhaps `testbed` needs to be enhanced with test for the multifinger taps?

I'm not sure I'm the best person to do that, but I can give a try if you want.

2025-01-26 21:07 UTC, raziel- commented
amigaos4 has just gotten an sdl3 rc
https://www.amigans.net/modules/newbb/viewtopic.php?post_id=152728#forumpost152728

not tested and i won't be able to do it anymore, but i guess sdl3 support will be possible

2025-01-27 16:20 UTC, raziel- commented
thank you very much
someone will be happy I'm sure 😀

2025-01-31 19:27 UTC, scemino commented
> Another bug: the ImGui window can't be moved outside the main window.

This one is fixed now!

2025-02-07 23:06 UTC, sev- commented
@scemino any plans to regenerate the patch so it shows less diff?

2025-02-07 23:07 UTC, sev- commented
I would like to merge it, so I could subsequently update ImGui, and the patch stays in the way.

2025-02-09 19:21 UTC, scemino commented
> @scemino any plans to regenerate the patch so it shows less diff?

For me it seems correct, the only big differences is the addition of `imgui_impl_sdlrenderer3.cpp` and `imgui_impl_sdlrenderer3.h`, can you point me out what's wrong?

2025-02-09 19:23 UTC, scemino commented
> I would like to merge it, so I could subsequently update ImGui, and the patch stays in the way.

I can drop my modifications on the patch, you want me to do that?

2025-02-16 22:07 UTC, sev- commented
> > @scemino any plans to regenerate the patch so it shows less diff?
> 
> For me it seems correct, the only big differences is the addition of `imgui_impl_sdlrenderer3.cpp` and `imgui_impl_sdlrenderer3.h`, can you point me out what's wrong?

No, it is not correct. You did not provide the paths exactly as it was before, as a result, we have a lot of noise like:

```diff
- diff --color -rbu ./backends/imgui_impl_opengl3.cpp - ../scummvm/scummvm/backends/imgui/backends/imgui_impl_opengl3.cpp
- --- ./backends/imgui_impl_opengl3.cpp	2024-10-07 18:21:01
- +++ ../scummvm/scummvm/backends/imgui/backends/imgui_impl_opengl3.cpp	2024-10-07 18:30:56
+ diff --git a/backends/imgui_impl_opengl3.cpp b/backends/imgui_impl_opengl3.cpp
+ index 770f85f4..b363ba07 100644
+ --- a/backends/imgui_impl_opengl3.cpp
+ +++ b/backends/imgui_impl_opengl3.cpp
@@ -114,7 +114,7 @@
 #define _CRT_SECURE_NO_WARNINGS
 #endif
-  
+
```

I am asking to do this for conistency, otherwise we end up with changing it every time.

2025-02-17 20:30 UTC, scemino commented
> > > @scemino any plans to regenerate the patch so it shows less diff?
> > 
> > 
> > For me it seems correct, the only big differences is the addition of `imgui_impl_sdlrenderer3.cpp` and `imgui_impl_sdlrenderer3.h`, can you point me out what's wrong?
> 
> No, it is not correct. You did not provide the paths exactly as it was before, as a result, we have a lot of noise like:
> 
> ```diff
> - diff --color -rbu ./backends/imgui_impl_opengl3.cpp - ../scummvm/scummvm/backends/imgui/backends/imgui_impl_opengl3.cpp
> - --- ./backends/imgui_impl_opengl3.cpp	2024-10-07 18:21:01
> - +++ ../scummvm/scummvm/backends/imgui/backends/imgui_impl_opengl3.cpp	2024-10-07 18:30:56
> + diff --git a/backends/imgui_impl_opengl3.cpp b/backends/imgui_impl_opengl3.cpp
> + index 770f85f4..b363ba07 100644
> + --- a/backends/imgui_impl_opengl3.cpp
> + +++ b/backends/imgui_impl_opengl3.cpp
> @@ -114,7 +114,7 @@
>  #define _CRT_SECURE_NO_WARNINGS
>  #endif
> -  
> +
> ```
> 
> I am asking to do this for conistency, otherwise we end up with changing it every time.

Sorry I'm not able to do it:

```
git diff --color -rbu > scummvm.patch
error: invalid option: -rbu
```

I removed the modifications on the patch.

2025-02-17 20:42 UTC, sev- commented
> git diff --color -rbu > scummvm.patch
> error: invalid option: -rbu

because it is NOT git. it is plain `diff` :D

Quoting my early reply:

> @scemino for generating patch, please use the same command as outlined in cff87d8c2e98b16f2669c54445f65240d23ecc9f
>
> ```bash
> diff -rbu . ../scummvm/scummvm/backends/imgui/|grep -v ^Only >../scummvm/scummvm/backends/imgui/scummvm.patch
> ```
> 
> This will remove those whitespace and file path changes.

Also, there are conflicts now, so the thing has to be rebased.

2025-02-17 20:44 UTC, sev- commented
> I removed the modifications on the patch.

I am using the patch for applying the changes on the ImGui upgrade. What is your proposed solution to this?

2025-02-18 20:12 UTC, scemino commented
> > git diff --color -rbu > scummvm.patch
> > error: invalid option: -rbu
> 
> because it is NOT git. it is plain `diff` :D `git diff` shows you the difference between commits, while here you need to store differences between ScummVM and ImGui repos.
> 
> Quoting my early reply:
> 
> > @scemino for generating patch, please use the same command as outlined in [cff87d8](https://github.com/scummvm/scummvm/commit/cff87d8c2e98b16f2669c54445f65240d23ecc9f)
> > ```shell
> > diff -rbu . ../scummvm/scummvm/backends/imgui/|grep -v ^Only >../scummvm/scummvm/backends/imgui/scummvm.patch
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will remove those whitespace and file path changes.
> 
> Also, there are conflicts now, so the thing has to be rebased.

OK I understand now, sorry about that.
I pushed the new patch file and then I will resolve the conflicts by rebasing.
I hope that if I rebase it, this PR won't be lost.

2025-02-18 21:13 UTC, sev- commented
Thank you, merging.

2025-02-18 21:13 UTC, merged

2025-02-19 00:56 UTC, sev- commented on configure
> +		_sdlconfig="pkg-config sdl3"
Ugh, I did not realize, that this breaks completely systems without pkg-config. Like mine....

2025-02-22 20:49 UTC, orgads commented
Thank you! Do you plan to add it also for create_project?